## Aim

To fetch data from a public REST API using Python, parse the JSON response, transform the retrieved data into a structured tabular format, perform basic data validation and preprocessing, and store the transformed data for further analysis.

## Theory

A **REST API (Representational State Transfer Application Programming Interface)** allows applications to communicate and exchange data over the internet. APIs commonly return data in **JSON (JavaScript Object Notation)** format, which is easy for programs to process.

In this experiment, Python was used to fetch data from a public REST API using the `requests` library. The JSON response was then parsed and converted into a Pandas DataFrame using `pandas.json_normalize()`.

Basic data validation was performed by checking:

* Missing values
* Duplicate records
* Data types
* Number of rows and columns

The data was then preprocessed by standardizing column names and removing duplicate records. Finally, the cleaned and transformed dataset was stored as a **CSV file** using Pandas' `to_csv()` function.

This process demonstrates a basic data pipeline for collecting, preparing, and storing data before further analysis.

In [ ]:
!pip install requests pandas

Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.7.22)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import requests
import pandas as pd

url = "https://jsonplaceholder.typicode.com/users"

response = requests.get(url)

print("Status Code:", response.status_code)

data = response.json()

print(data[:2])

Status Code: 200
[{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}, {'id': 2, 'name': 'Ervin Howell', 'username': 'Antonette', 'email': 'Shanna@melissa.tv', 'address': {'street': 'Victor Plains', 'suite': 'Suite 879', 'city': 'Wisokyburgh', 'zipcode': '90566-7771', 'geo': {'lat': '-43.9509', 'lng': '-34.4618'}}, 'phone': '010-692-6593 x09125', 'website': 'anastasia.net', 'company': {'name': 'Deckow-Crist', 'catchPhrase': 'Proactive didactic contingency', 'bs': 'synergize scalable supply-chains'}}]

In [ ]:
df = pd.json_normalize(data)

print(df.head())
print("\nShape:", df.shape)

   id              name   username                      email  \
0   1     Leanne Graham       Bret          Sincere@april.biz
1   2      Ervin Howell  Antonette          Shanna@melissa.tv
2   3  Clementine Bauch   Samantha         Nathan@yesenia.net
3   4  Patricia Lebsack   Karianne  Julianne.OConner@kory.org
4   5  Chelsey Dietrich     Kamren   Lucio_Hettinger@annie.ca

                   phone        website     address.street address.suite  \
0  1-770-736-8031 x56442  hildegard.org        Kulas Light      Apt. 556
1    010-692-6593 x09125  anastasia.net      Victor Plains     Suite 879
2         1-463-123-4447    ramiro.info  Douglas Extension     Suite 847
3      493-170-9623 x156       kale.biz        Hoeger Mall      Apt. 692
4          (254)954-1289   demarco.info       Skiles Walks     Suite 351

    address.city address.zipcode address.geo.lat address.geo.lng  \
0    Gwenborough      92998-3874        -37.3159         81.1496
1    Wisokyburgh      90566-7771        -43.9509        -34.4618
2  McKenziehaven      59590-4157        -68.6102        -47.0653
3    South Elvis      53919-4257         29.4572       -164.2990
4     Roscoeview           33263        -31.8129         62.5342

         company.name                       company.catchPhrase  \
0     Romaguera-Crona    Multi-layered client-server neural-net
1        Deckow-Crist            Proactive didactic contingency
2  Romaguera-Jacobson         Face to face bifurcated interface
3       Robel-Corkery  Multi-tiered zero tolerance productivity
4         Keebler LLC      User-centric fault-tolerant solution

                             company.bs
0           harness real-time e-markets
1      synergize scalable supply-chains
2       e-enable strategic applications
3  transition cutting-edge web services
4      revolutionize end-to-end systems

Shape: (10, 15)

In [ ]:
print("Missing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

print("\nNumber of rows and columns:")
print(df.shape)

Missing values:
id                     0
name                   0
username               0
email                  0
phone                  0
website                0
address.street         0
address.suite          0
address.city           0
address.zipcode        0
address.geo.lat        0
address.geo.lng        0
company.name           0
company.catchPhrase    0
company.bs             0
dtype: int64

Duplicate rows: 0

Data types:
id                      int64
name                   object
username               object
email                  object
phone                  object
website                object
address.street         object
address.suite          object
address.city           object
address.zipcode        object
address.geo.lat        object
address.geo.lng        object
company.name           object
company.catchPhrase    object
company.bs             object
dtype: object

Number of rows and columns:
(10, 15)

In [ ]:
df.columns = df.columns.str.replace(".", "_", regex=False)

df = df.drop_duplicates()

df = df.drop(columns=["address_geo_lat", "address_geo_lng"], errors="ignore")

print(df.head())

   id              name   username                      email  \
0   1     Leanne Graham       Bret          Sincere@april.biz
1   2      Ervin Howell  Antonette          Shanna@melissa.tv
2   3  Clementine Bauch   Samantha         Nathan@yesenia.net
3   4  Patricia Lebsack   Karianne  Julianne.OConner@kory.org
4   5  Chelsey Dietrich     Kamren   Lucio_Hettinger@annie.ca

                   phone        website     address_street address_suite  \
0  1-770-736-8031 x56442  hildegard.org        Kulas Light      Apt. 556
1    010-692-6593 x09125  anastasia.net      Victor Plains     Suite 879
2         1-463-123-4447    ramiro.info  Douglas Extension     Suite 847
3      493-170-9623 x156       kale.biz        Hoeger Mall      Apt. 692
4          (254)954-1289   demarco.info       Skiles Walks     Suite 351

    address_city address_zipcode        company_name  \
0    Gwenborough      92998-3874     Romaguera-Crona
1    Wisokyburgh      90566-7771        Deckow-Crist
2  McKenziehaven      59590-4157  Romaguera-Jacobson
3    South Elvis      53919-4257       Robel-Corkery
4     Roscoeview           33263         Keebler LLC

                        company_catchPhrase  \
0    Multi-layered client-server neural-net
1            Proactive didactic contingency
2         Face to face bifurcated interface
3  Multi-tiered zero tolerance productivity
4      User-centric fault-tolerant solution

                             company_bs
0           harness real-time e-markets
1      synergize scalable supply-chains
2       e-enable strategic applications
3  transition cutting-edge web services
4      revolutionize end-to-end systems

In [ ]:
df["valid_email"] = df["email"].str.contains("@", na=False)

print(df[["email", "valid_email"]])

                       email  valid_email
0          Sincere@april.biz         True
1          Shanna@melissa.tv         True
2         Nathan@yesenia.net         True
3  Julianne.OConner@kory.org         True
4   Lucio_Hettinger@annie.ca         True
5    Karley_Dach@jasper.info         True
6     Telly.Hoeger@billy.biz         True
7       Sherwood@rosamond.me         True
8    Chaim_McDermott@dana.io         True
9     Rey.Padberg@karina.biz         True

In [ ]:
df.to_csv("users_transformed.csv", index=False)

print("Data successfully saved as users_transformed.csv")

Data successfully saved as users_transformed.csv

In [ ]:
# Convert JSON data into a Pandas DataFrame
df = pd.json_normalize(data)

print("Data in tabular format:")
display(df)

Data in tabular format:

,id,name,username,email,phone,website,address.street,address.suite,address.city,address.zipcode,address.geo.lat,address.geo.lng,company.name,company.catchPhrase,company.bs
0,1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,hildegard.org,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,anastasia.net,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,ramiro.info,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,kale.biz,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,demarco.info,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,1-477-935-8478 x6430,ola.org,Norberto Crossing,Apt. 950,South Christy,23505-1337,-71.4197,71.7478,Considine-Lockman,Synchronised bottom-line interface,e-enable innovative applications
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,210.067.6132,elvis.io,Rex Trail,Suite 280,Howemouth,58804-1099,24.8918,21.8984,Johns Group,Configurable multimedia task-force,generate enterprise e-tailers
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,586.493.6943 x140,jacynthe.com,Ellsworth Summit,Suite 729,Aliyaview,45169,-14.3990,-120.7677,Abernathy Group,Implemented secondary concept,e-enable extensible e-tailers
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,(775)976-6794 x41206,conrad.com,Dayna Park,Suite 449,Bartholomebury,76495-3109,24.6463,-168.8889,Yost and Sons,Switchable contextually-based project,aggregate real-time technologies
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,024-648-3804,ambrose.net,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,-38.2386,57.2232,Hoeger LLC,Centralized empowering task-force,target end-to-end models

In [ ]:
# Basic data validation

print("Number of rows and columns:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Number of rows and columns: (10, 15)

Missing values:
id                     0
name                   0
username               0
email                  0
phone                  0
website                0
address.street         0
address.suite          0
address.city           0
address.zipcode        0
address.geo.lat        0
address.geo.lng        0
company.name           0
company.catchPhrase    0
company.bs             0
dtype: int64

Duplicate rows: 0

Data types:
id                      int64
name                   object
username               object
email                  object
phone                  object
website                object
address.street         object
address.suite          object
address.city           object
address.zipcode        object
address.geo.lat        object
address.geo.lng        object
company.name           object
company.catchPhrase    object
company.bs             object
dtype: object

In [ ]:
# Preprocessing

# Make column names simple
df.columns = df.columns.str.replace(".", "_", regex=False)

# Remove duplicate records
df = df.drop_duplicates()

print("Preprocessed Data:")
display(df)

Preprocessed Data:

,id,name,username,email,phone,website,address_street,address_suite,address_city,address_zipcode,address_geo_lat,address_geo_lng,company_name,company_catchPhrase,company_bs
0,1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,hildegard.org,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,anastasia.net,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,ramiro.info,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,kale.biz,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,demarco.info,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,1-477-935-8478 x6430,ola.org,Norberto Crossing,Apt. 950,South Christy,23505-1337,-71.4197,71.7478,Considine-Lockman,Synchronised bottom-line interface,e-enable innovative applications
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,210.067.6132,elvis.io,Rex Trail,Suite 280,Howemouth,58804-1099,24.8918,21.8984,Johns Group,Configurable multimedia task-force,generate enterprise e-tailers
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,586.493.6943 x140,jacynthe.com,Ellsworth Summit,Suite 729,Aliyaview,45169,-14.3990,-120.7677,Abernathy Group,Implemented secondary concept,e-enable extensible e-tailers
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,(775)976-6794 x41206,conrad.com,Dayna Park,Suite 449,Bartholomebury,76495-3109,24.6463,-168.8889,Yost and Sons,Switchable contextually-based project,aggregate real-time technologies
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,024-648-3804,ambrose.net,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,-38.2386,57.2232,Hoeger LLC,Centralized empowering task-force,target end-to-end models

In [ ]:
# Save the transformed data as CSV

df.to_csv("users_transformed.csv", index=False)

print("Data successfully saved as users_transformed.csv")

Data successfully saved as users_transformed.csv

In [ ]:
print("Final Dataset Shape:", df.shape)
print("\nFinal Columns:")
print(df.columns.tolist())

print("\nFirst 5 Records:")
display(df.head())

print("\nAssignment completed successfully!")

Final Dataset Shape: (10, 15)

Final Columns:
['id', 'name', 'username', 'email', 'phone', 'website', 'address_street', 'address_suite', 'address_city', 'address_zipcode', 'address_geo_lat', 'address_geo_lng', 'company_name', 'company_catchPhrase', 'company_bs']

First 5 Records:

,id,name,username,email,phone,website,address_street,address_suite,address_city,address_zipcode,address_geo_lat,address_geo_lng,company_name,company_catchPhrase,company_bs
0,1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,hildegard.org,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,anastasia.net,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,ramiro.info,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,kale.biz,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,demarco.info,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems

Assignment completed successfully!

## Conclusion

The experiment was successfully completed by fetching data from a public REST API and converting the JSON response into a structured Pandas DataFrame. The data was validated, cleaned, and preprocessed before being stored as a CSV file. This experiment demonstrated how Python can be used to automate the basic process of collecting and preparing API data for further analysis.